name: Periodic Health Check

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Ping server
        id: ping
        run: 
          curl -f https://fullstack-cicd.onrender.com/

      - name: Send success message to Discord
        if: success()
        uses: uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Health check OK: site is up"

      - name: Send failure message to Discord
        if: failure()
        uses: uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "Health check FAILED: site is down"
