name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Trigger render deploy
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"
      - name: Check deploy hook exists
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "RENDER_DEPLOY_HOOK is missing"
            exit 1
          fi
